### ISSUE TITLE
error creating /tmp/.wine-0/server-9a-6800a/lock: Read-only file system

### ISSUE THREAD

**Issue by vebeToken** [mgalos999/d2-mapper#1]
Hey i get Read only file System.

wine bin/d2-map.exe game --seed 10 --level 1 --difficulty 0    worked well. 

But after that i cant do nothing. 

docker run -v "/E/Games/Diablo II":/app/game -p 8899:8899 docker.io/blacha/diablo2:latest  after typing this in im getting:

error creating /tmp/.wine-0/server-9a-6800a/lock: Read-only file system

**Comment by mgalos999** [comment]
Check that your Diablo 2 installation (not resurrected) is in the path you specified /E/Games/Diablo II.
But this is for a separate Github project written by someone else, please raise your issue there: https://github.com/blacha/diablo2/tree/master/packages/map
